Repository AGH-Narzedzia-Informatyczne-2022-2023/MontePyton, pull requests merged in 2022-11, with the labels that each got.

#8 Create main.py
  main.py
Labels: documentation, Indywidualne

#7 Create boxColliderObject
  .game/_objects/boxColliderObject
Labels: Indywidualne

#11 Create gameObject.py
  gameObject.py
Labels: help wanted, Indywidualne

#12 Create spriteObject.py
  spriteObject.py
Labels: help wanted, invalid

#17 2nd branch
  ObjectFromCanvas.py
Labels: enhancement
